import { Booleanish, numOrStr } from '../common'
import { AriaAttributes, AriaRole } from './aria'
import { DOMAttributes } from './html-attributes'

//   - union of string literals
interface SVGAttributes<T> extends AriaAttributes, DOMAttributes<T> {
  // Attributes which also defined in HTMLAttributes
  class?: string
  color?: string
  height?: numOrStr
  id?: string
  lang?: string
  max?: numOrStr
  media?: string
  method?: string
  min?: numOrStr
  name?: string
  style?: string
  target?: string
  type?: string
  width?: numOrStr

  // Other HTML properties supported by SVG elements in browsers
  role?: AriaRole
  tabindex?: number
  crossorigin?: 'anonymous' | 'use-credentials' | ''

  // SVG Specific attributes
  accentheight?: numOrStr
  accumulate?: 'none' | 'sum'
  additive?: 'replace' | 'sum'
  alignmentbaseline?:
    | 'auto'
    | 'baseline'
    | 'before-edge'
    | 'text-before-edge'
    | 'middle'
    | 'central'
    | 'after-edge'
    | 'text-after-edge'
    | 'ideographic'
    | 'alphabetic'
    | 'hanging'
    | 'mathematical'
    | 'inherit'
    | undefined
  allowreorder?: 'no' | 'yes'
  alphabetic?: numOrStr
  amplitude?: numOrStr
  arabicform?: 'initial' | 'medial' | 'terminal' | 'isolated'
  ascent?: numOrStr
  attributename?: string
  attributetype?: string
  autoreverse?: Booleanish
  azimuth?: numOrStr
  basefrequency?: numOrStr
  baselineshift?: numOrStr
  baseprofile?: numOrStr
  bbox?: numOrStr
  begin?: numOrStr
  bias?: numOrStr
  by?: numOrStr
  calcmode?: numOrStr
  capheight?: numOrStr
  clip?: numOrStr
  clippath?: string
  clippathunits?: numOrStr
  cliprule?: numOrStr
  colorinterpolation?: numOrStr
  colorinterpolationfilters?: 'auto' | 'srgb' | 'linearrgb' | 'inherit'
  colorprofile?: numOrStr
  colorrendering?: numOrStr
  contentscripttype?: numOrStr
  contentstyletype?: numOrStr
  cursor?: numOrStr
  cx?: numOrStr
  cy?: numOrStr
  d?: string
  decelerate?: numOrStr
  descent?: numOrStr
  diffuseconstant?: numOrStr
  direction?: numOrStr
  display?: numOrStr
  divisor?: numOrStr
  dominantbaseline?: numOrStr
  dur?: numOrStr
  dx?: numOrStr
  dy?: numOrStr
  edgemode?: numOrStr
  elevation?: numOrStr
  enablebackground?: numOrStr
  end?: numOrStr
  exponent?: numOrStr
  externalresourcesrequired?: Booleanish
  fill?: string
  fillopacity?: numOrStr
  fillrule?: 'nonzero' | 'evenodd' | 'inherit'
  filter?: string
  filterres?: numOrStr
  filterunits?: numOrStr
  floodcolor?: numOrStr
  floodopacity?: numOrStr
  focusable?: Booleanish | 'auto'
  fontfamily?: string
  fontsize?: numOrStr
  fontsizeadjust?: numOrStr
  fontstretch?: numOrStr
  fontstyle?: numOrStr
  fontvariant?: numOrStr
  fontweight?: numOrStr
  format?: numOrStr
  fr?: numOrStr
  from?: numOrStr
  fx?: numOrStr
  fy?: numOrStr
  g1?: numOrStr
  g2?: numOrStr
  glyphname?: numOrStr
  glyphorientationhorizontal?: numOrStr
  glyphorientationvertical?: numOrStr
  glyphref?: numOrStr
  gradienttransform?: string
  gradientunits?: string
  hanging?: numOrStr
  horizadvx?: numOrStr
  horizoriginx?: numOrStr
  href?: string
  ideographic?: numOrStr
  imagerendering?: numOrStr
  in2?: numOrStr
  in?: string
  intercept?: numOrStr
  k1?: numOrStr
  k2?: numOrStr
  k3?: numOrStr
  k4?: numOrStr
  k?: numOrStr
  kernelmatrix?: numOrStr
  kernelunitlength?: numOrStr
  kerning?: numOrStr
  keypoints?: numOrStr
  keysplines?: numOrStr
  keytimes?: numOrStr
  lengthadjust?: numOrStr
  letterspacing?: numOrStr
  lightingcolor?: numOrStr
  limitingconeangle?: numOrStr
  local?: numOrStr
  markerend?: string
  markerheight?: numOrStr
  markermid?: string
  markerstart?: string
  markerunits?: numOrStr
  markerwidth?: numOrStr
  mask?: string
  maskcontentunits?: numOrStr
  maskunits?: numOrStr
  mathematical?: numOrStr
  mode?: numOrStr
  numoctaves?: numOrStr
  offset?: numOrStr
  opacity?: numOrStr
  operator?: numOrStr
  order?: numOrStr
  orient?: numOrStr
  orientation?: numOrStr
  origin?: numOrStr
  overflow?: numOrStr
  overlineposition?: numOrStr
  overlinethickness?: numOrStr
  paintorder?: numOrStr
  panose1?: numOrStr
  path?: string
  pathlength?: numOrStr
  patterncontentunits?: string
  patterntransform?: numOrStr
  patternunits?: string
  pointerevents?: numOrStr
  points?: string
  pointsatx?: numOrStr
  pointsaty?: numOrStr
  pointsatz?: numOrStr
  preservealpha?: Booleanish
  preserveaspectratio?: string
  primitiveunits?: numOrStr
  r?: numOrStr
  radius?: numOrStr
  refx?: numOrStr
  refy?: numOrStr
  renderingintent?: numOrStr
  repeatcount?: numOrStr
  repeatdur?: numOrStr
  requiredextensions?: numOrStr
  requiredfeatures?: numOrStr
  restart?: numOrStr
  result?: string
  rotate?: numOrStr
  rx?: numOrStr
  ry?: numOrStr
  scale?: numOrStr
  seed?: numOrStr
  shaperendering?: numOrStr
  slope?: numOrStr
  spacing?: numOrStr
  specularconstant?: numOrStr
  specularexponent?: numOrStr
  speed?: numOrStr
  spreadmethod?: string
  startoffset?: numOrStr
  stddeviation?: numOrStr
  stemh?: numOrStr
  stemv?: numOrStr
  stitchtiles?: numOrStr
  stopcolor?: string
  stopopacity?: numOrStr
  strikethroughposition?: numOrStr
  strikethroughthickness?: numOrStr
  string?: numOrStr
  stroke?: string
  strokedasharray?: numOrStr
  strokedashoffset?: numOrStr
  strokelinecap?: 'butt' | 'round' | 'square' | 'inherit'
  strokelinejoin?: 'miter' | 'round' | 'bevel' | 'inherit'
  strokemiterlimit?: numOrStr
  strokeopacity?: numOrStr
  strokewidth?: numOrStr
  surfacescale?: numOrStr
  systemlanguage?: numOrStr
  tablevalues?: numOrStr
  targetx?: numOrStr
  targety?: numOrStr
  textanchor?: string
  textdecoration?: numOrStr
  textlength?: numOrStr
  textrendering?: numOrStr
  to?: numOrStr
  transform?: string
  u1?: numOrStr
  u2?: numOrStr
  underlineposition?: numOrStr
  underlinethickness?: numOrStr
  unicode?: numOrStr
  unicodebidi?: numOrStr
  unicoderange?: numOrStr
  unitsperem?: numOrStr
  valphabetic?: numOrStr
  values?: string
  vectoreffect?: numOrStr
  version?: string
  vertadvy?: numOrStr
  vertoriginx?: numOrStr
  vertoriginy?: numOrStr
  vhanging?: numOrStr
  videographic?: numOrStr
  viewbox?: string
  viewtarget?: numOrStr
  visibility?: numOrStr
  vmathematical?: numOrStr
  widths?: numOrStr
  wordspacing?: numOrStr
  writingmode?: numOrStr
  x1?: numOrStr
  x2?: numOrStr
  x?: numOrStr
  xchannelselector?: string
  xheight?: numOrStr
  xlinkactuate?: string
  xlinkarcrole?: string
  xlinkhref?: string
  xlinkrole?: string
  xlinkshow?: string
  xlinktitle?: string
  xlinktype?: string
  xmlbase?: string
  xmllang?: string
  xmlns?: string
  xmlnsxlink?: string
  xmlspace?: string
  y1?: numOrStr
  y2?: numOrStr
  y?: numOrStr
  ychannelselector?: string
  z?: numOrStr
  zoomandpan?: string
}
